### ISSUE TITLE
how to display a table if i don't know column names?

### ISSUE THREAD

**Issue by guchengxi1994** [caduandrade/easy_table_flutter#31]
I want to display a sheet from a xlsx file but i don't know how many columns and what column names are , how should i use this repo?

**Comment by caduandrade** [comment]
Hi @guchengxi1994 ! Sorry, I didn't understand the question. If you don't want to display a name in the column, you can use an empty String. This API does not automatically load `xlsx` files. You will have to manually open the file and create the table model with the columns you want.

**Comment by guchengxi1994** [comment]
@caduandrade I found out a solution like this,
![image](https://user-images.githubusercontent.com/33513462/172270392-3b76d6b0-c18d-4db6-8bbe-9dd19da96971.png)
 but I have another question, every time my mouse hover on rows will execute these codes, like this

![20220607](https://user-images.githubusercontent.com/33513462/172270744-ba6fa9d2-941a-40de-8d36-b0458517e98a.gif)

i dont know why and i am not sure will it  affect performance

**Comment by caduandrade** [comment]
Since you are using a `cellBuilder`, the behavior is like `ListView.builder`. Will create a widget for each cell. It's happening because of the mouse highlight color. Maybe I can even improve it. I'll try to keep this color on background without having to reconstruct the cells. I will see that.

But for better performance, the ideal is to use `stringValue` instead of `cellBuilder`. This one will not instantiate `Text` widget. It will draw the text directly on the canvas.

**Comment by guchengxi1994** [comment]
Ok, I will use `stringValue` instead, thanks a lot
