### ISSUE TITLE
Infinite scroll is not working

### ISSUE THREAD

**Issue by lpemeg** [caduandrade/easy_table_flutter#41]
Infinite scroll is not working, the onLastRowWidget, when it reaches the last line, is not executed.

**Comment by caduandrade** [comment]
Hi @lpemeg !

I believe you did something wrong. You can check the demo or examples. Since you didn't post your code, I don't know if I can help you.

Maybe you only set `onLastVisibleRow` and missed `lastRowWidget` Widget.
The `onLastVisibleRow` listener only fires when the `lastRowWidget` Widget is visible. It was made to be used together.

If you don't want to add an extra widget at the end, you can use the `onLastVisibleRow` listener which monitors the last visible row.

And I should add more documentation in the code :wink:

**Comment by lpemeg** [comment]
Entendi obg, vou tentar aqui se não consegui vou postar meu código

**Comment by lpemeg** [comment]
Finalizando o post ficou perfeito seu codigo é perfeito muito obg.

**Comment by caduandrade** [comment]
Valeu!

O exemplo usa só a combinação `lastRowWidget` e `onLastRowWidget` para adicionar um Widget extra. Vale lembrar que esse Widget não é considerado uma linha do modelo. Talvez os nomes não estejam ajudando. Talvez `lastRowWidget` deveria se chamar `lastWidget`, `widgetAfterLastRow` ou algo assim. 

Já o `onLastVisibleRow` é outra maneira de implementar onde exibe a última linha do modelo visível. Esse não contabiliza o `lastRowWidget`. 

Qualquer coisa avisa. :+1:

**Comment by lpemeg** [comment]
Pois é amigo quando faço a junção dos 2 lastRowWidget e onLastRowWidget, a ideia seria que quando eu rolasse e mostrasse o widget do carregamento ele executasse o onLasRowWidget pois estaria visivel ou entendi errado, estando ele visivel carregaria o proximo é ai que no meu caso não carregou só começou a executar o onLastRowWidget quando coloquei o onLastVisibleRow.
